# Generated by Django 3.1.4 on 2020-12-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='url',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
