# Generated by Django 3.1.4 on 2020-12-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
