# Generated by Django 3.1.4 on 2020-12-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0003_auto_20201205_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='plate',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='plates'),
        ),
    ]
